clusterDescription: Test cluster.
organization: giantswarm-2
cloudConfig: cloud-config
cloudName: openstack
nodeCIDR: 10.6.0.0/24
dnsNameservers:
- 8.8.8.8
- 1.1.1.1

kubernetesVersion: 1.20.9
releaseVersion: 20.0.0-alpha1

externalNetworkID: 1700ba33-e871-4893-8a05-b5b564154eed

rootVolume:
  enabled: true
  sourceUUID: 90b7124a-c526-4477-b6b3-73996a3c85be

controlPlane:
  replicas: 1

nodeClasses:
- name: default
  machineFlavor: n1.small
  diskSize: 50

nodePools:
- name: default
  class: default
  replicas: 3
